In [1]:
# Linear Algebra Assignment
# Use you Jupyterlab environment and numpy to solve the attached systems of equations. What values do you get for x and y for each?

# 3x + 5y = 6
# 7x - 5y = 9

# x + y + z = 6
#     y + z = -4

# 2x + 5y - z = 27
# x + y = 4
# 2x + 2y = 8
# What happens with the last solution? Why?   

In [31]:
# Problem 1
# 3x + 5y = 6
# 7x - 5y = 9
import numpy as np

In [26]:
a = np.array([[3, 5],
             [7, -5]])

In [27]:
b = np.array([[6],[9]])

In [28]:
print(a)

[[ 3  5]
 [ 7 -5]]


In [29]:
print(b)

[[6]
 [9]]


In [30]:
np.linalg.solve(a,b)

array([[1.5],
       [0.3]])

In [12]:
# Problem 2
# x + y + z = 6
#     y + z = -4
#2x + 5y - z = 27



In [46]:
c = np.array([[1, 1, 1], [0, 1, 1], [2, 5, -1]])

In [51]:
d = np.array([[6],[ -4], [27]])

In [49]:
np.linalg.solve(c,d)

array([[10. ],
       [ 0.5],
       [-4.5]])

In [50]:
#Problem 3
# 2x + 5y - z = 27
# x + y = 4
# 2x + 2y = 8

In [53]:
e = np.array([[2,5,-1], [1,1,0], [2,2,0]])

In [54]:
f = np.array([[27],[4],[8]])

In [55]:
np.linalg.solve(e,f)

LinAlgError: Singular matrix

In [ ]:
#Singular matrix = Vector matrix